services:
  devcontainer: 
    image: mcr.microsoft.com/devcontainers/base:bullseye
    volumes:
      - ..:/workspace:cached
    environment:
      - NODE_ENV=development
    command: sleep infinity
    network_mode: service:webdav
  webdav:
    image: bytemark/webdav
    restart: unless-stopped
    ports:
      - "80:8081"
    environment:
      AUTH_TYPE: Digest
      USERNAME: alice
      PASSWORD: secret1234
      ANONYMOUS_METHODS: ALL
    volumes:
      - ../dist:/var/lib/dav/data

